#!/bin/bash
#version 0.3
#by Patryk Basko
#in this version script is in "verbose" mode

date=$(date +%D)
#defined colors, NC use to disable painting
R='\033[0;31m'
G='\033[0;32m'
Y='\033[0;33m'
NC='\033[0m'
count=1

while IFS= read -r line
do
        echo -e "\n${G}$line${NC}"
                password=$( tr -dc '[:lower:][:upper:][:digit:]@_' < /dev/urandom | head -c 20)
                echo "Password before looping and if: $password"
                if [[ $password =~ [[:lower:]] && $password =~ [[:upper:]] && $password =~ [[:digit:]] && $password =~ "@" && $password =~ "_" ]]; then
                        echo -e "Password is ${G}correct${NC}: $password"
                        else
                        until [[ $password =~ [[:lower:]] && $password =~ [[:upper:]] && $password =~ [[:digit:]] && $password =~ "@" && $password =~ "_" ]]; do
                        #char_4=$(echo "${password:$(( RANDOM % ${#password} )):2}")
                        #new_password=$(echo "$password" | sed "s/$char_4/@_/g")
                        password=$( tr -dc '[:lower:][:upper:][:digit:]@_' < /dev/urandom | head -c 20)
                        ((count++))
                        #password=$new_password
                        done
                        echo -e "Password was ${Y}generated${NC}: $password"

                fi
                echo "Count operation: $count"

done < /root/custom_users
